export const GET_GENRE_SUCCESS = 'GET_GENRE_SUCCESS'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS'

export const CLEAR_MOVIES = 'CLEAR_MOVIES'

export const CALLING_API = 'CALLING_API'
export const ERROR = 'ERROR'
