export const GET_GENRE_SUCCESS = 'GET GENRE SUCCESS'
export const GET_MOVIES_SUCCESS = 'GET MOVIES SUCCESS'
export const GET_MOVIE_DETAIL_SUCCESS = 'GET MOVIE DETAIL SUCCESS'

export const CLEAR_MOVIES = 'CLEAR MOVIES'

export const CALLING_API = 'CALLING API'
export const ERROR = 'ERROR'

export const ADD_MOVIE_TO_CART = 'ADD MOVIE TO CART'

export const CHANGE_LOCATION = 'CHANGE LOCATION'
